# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

confint_binom_cpp <- function(n, N, cl, p_min, p_max, p_step) {
    .Call(`_fcci_confint_binom_cpp`, n, N, cl, p_min, p_max, p_step)
}

confint_pois_cpp <- function(n, b, cl, lambda_min, lambda_max, lambda_step) {
    .Call(`_fcci_confint_pois_cpp`, n, b, cl, lambda_min, lambda_max, lambda_step)
}

confint_pois_adj_cpp <- function(n, b, cl, lambda_min, lambda_max, lambda_step, b_max, b_step) {
    .Call(`_fcci_confint_pois_adj_cpp`, n, b, cl, lambda_min, lambda_max, lambda_step, b_max, b_step)
}

