# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binom_confint_cpp <- function(n, N, cl, p_min, p_max, p_step) {
    .Call(`_fcci_binom_confint_cpp`, n, N, cl, p_min, p_max, p_step)
}

pois_confint_cpp <- function(n, b, cl, lambda_min, lambda_max, lambda_step) {
    .Call(`_fcci_pois_confint_cpp`, n, b, cl, lambda_min, lambda_max, lambda_step)
}

pois_confint_cpp_adjusted <- function(n, b, cl, lambda_min, lambda_max, lambda_step, b_max = 0, b_step = 0) {
    .Call(`_fcci_pois_confint_cpp_adjusted`, n, b, cl, lambda_min, lambda_max, lambda_step, b_max, b_step)
}

